name: cifar10 iid AFL
on: workflow_dispatch

jobs:
  deploy:
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run experiment
        run:  python main.py --dataset cifar10 --data_dist iid --federated_type afl
