name: fmnist iid FedAvg
on: workflow_dispatch

jobs:
  deploy:
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run experiment
        run:  python main.py --dataset fmnist --data_dist iid --federated_type fedavg
